### ISSUE TITLE
Tab trigger bloginfo-> doesn't work

### ISSUE THREAD

**Issue by ghost** [Gipetto/wordpress.tmbundle#16]
First of all, thank you for this awesome bundle! It makes learning WP theme development much easier.

I do have a slight problem; whenever I tab after typing bloginfo, I get something like this: /tmp/temp_textmate.6FAEts:6:in . The string changes every time I try it, the only part that remains the same is /tmp/temp_textmate.[changes]:6:in .

I tried to search for an solution, but couldn't find any. Some help will be appreciated and thanks in advance!

**Comment by Gipetto** [comment]
Sorry for getting back late on this. I'll get this checked out as soon as I can. I have an inkling as to what it is...

**Comment by ghost** [comment]
@Gipetto: No problem, thank you for looking into it!

**Comment by ghost** [comment]
Whoops, wrong button..

**Comment by Gipetto** [comment]
I can't replicate this. Can you post the full error as is pops up?

**Comment by joshbrown** [comment]
@Gipetto Here is the error that is coming up: `bloginfo...:5: undefined method`+' for nil:NilClass (NoMethodError)`

This is happening in TextMate Version 2.0 (8971)

**Comment by joshbrown** [comment]
@Gipetto TextMate 2.0 doesn't use `TM_BUNDLE_PATH` anymore `TM_BUNDLE_SUPPORT` is now used.

I'll see what I can do to help you fix this error in TM2.

_EDIT_: One more note, `TM_BUNDLE_SUPPORT` points directly to `/Users/USER/Library/Application Support/TextMate/Managed/Bundles/BUNDLENAME/Support/`

So in the cases where you have `path = ENV['TM_BUNDLE_SUPPORT'] + '/Support/common.rb'` should be `path = ENV['TM_BUNDLE_SUPPORT'] + '/common.rb'`

**Comment by Gipetto** [comment]
Yeah, I've got the bundle working locally but haven't had the time to push the change public yet because I haven't had the chance to do the backwards compatible testing. 

I hope to have the bundle updated for WP 3.3 and TM 2 soon.

**Comment by Gipetto** [comment]
Please, though, if you have working and tested code committed you can submit a pull request against master and I'll merge your changes in.

**Comment by joshbrown** [comment]
I will see what I can do to contribute later this week :)

**Comment by Gipetto** [comment]
I think I got it the TM2 support nailed down. Code is up in Master.

**Comment by ghost** [comment]
Sorry for the awful late reply, it seems that the problem is solved. Thanks for the support :) Shall we close this issue?

**Comment by joshbrown** [comment]
Yes!

**Comment by ghost** [comment]
Solved
