### ISSUE TITLE
Corrections/additions to custom_post_type snippet

### ISSUE THREAD

**Issue by simonwheatley** [Gipetto/wordpress.tmbundle#18]
Corrected `publically_queryable` to `publicly_queryable` and added localisation domains to `__` function calls.

You can grab them from https://github.com/simonwheatley/wordpress.tmbundle/commit/f623e5307466d1964793e16e95d4537544188151 if you like.

Cheers,

Simon

**Comment by Gipetto** [comment]
This has been merged. Thanks!
