### ISSUE TITLE
Add shortcut for internationalization of strings

### ISSUE THREAD

**Issue by gordonbrander** [Gipetto/wordpress.tmbundle#8]
Wouldn't this be nice:
- Highlight a selection of text (e.g. `my text string`) and hit a key combo
- Text is automatically wrapped in a WP i18n function and you're dropped into the language key param: `_e('my text string', '')`.
- Add a shortcut for both HTML and PHP scope. If in the HTML scope, the function is automatically wrapped in a PHP tag.

**Comment by Gipetto** [comment]
This is done. Quick block post on how to use it here: http://top-frog.com/?p=1319

The textmate variable WP_TEXT_DOMAIN will be supported in the 3.0 version of the plugin (currently under development in the 3.0 branch)

**Comment by Gipetto** [comment]
done. closing.
